### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a button to get your app on F-Droid 👍 

I removed the button redirecting to the repo of @IzzySoft You might want to tell him if you want to keep your app in his repo or not.

You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.

### CODE REVIEW

**Comment by Bnyro** [comment]
Thank you!

**Comment by IzzySoft** [comment]
Marked accordingly, thanks! Then it's just your clock, contacts, translate and wallpaper remaining here – as long as you want them to stay :smiley:

**Comment by Bnyro** [comment]
Damn, we're slowly running out of apps :wink:
LibreTube is still in your repo though, so we're currently at 5 apps :)

**Comment by Bnyro** [comment]
Since we're just talking here currently, I quickly want to ask a question:
Someone has taken the effort to create uniform icons for all the Bnyro apps which will get into action with the next update.
Will the F-Droid repo and your repo automatically update the icon displayed in the repo according to the fastlane icon.png? Or will it need to get updated manually?

**Comment by IzzySoft** [comment]
F-Droid should pick automatically whatever is available in Fastlane. My updater only picks what I tell it to (quality reasons; you won't believe what folks put there considering a screenshot an icon, a portrait a featureGraphic, some wall-of-text a full description etc). So should it not show up with mine, drop me a note and I'll check. Or wait a few days until my monthly QS-Check reports it to me – but that will do so only if I didn't explicitly set the icon to "ignore" because you e.g. used some pr0n pr0m0 as icon :see_no_evil:

And apologies I forgot to count LibreTube: guess that uses an `applicationid` not matching the patterns of the other ones :wink:

**Comment by Bnyro** [comment]
Okay, awesome! It can probably take some days until I actually start publishing the updates with the new icon, I guess it's sufficient to just wait until you would pick it up anyways :)

Though when F-Droid picks them up automatically, I really wonder how K haven't yet seen any weird apps with strange content on F-Droid, if it's so easy to abuse apparently. Very interesting!

PS: Indeed LibreTube uses a different app ID and you can't really tell it mine either since a lot of other people have been contributing to it too, I'm just its admin 😜

**Comment by IzzySoft** [comment]
> any weird apps with strange content

It's not simply copied, but of course "pruned" (in my repo, too). Not saying there'd be no way to mess up, though. I vaguely remember there was e.g. some app with "NSFW pics" we had to remove after they've been reported.

**Pull request merged**
