### PR TITLE
Show video thumbnails in recordings view

### PR DESCRIPTION
**Pull request by SuhasDissa**
| Before                                                                                                          | After                                                                                                           |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
|  |  |

### CODE REVIEW

**Comment by SuhasDissa** [comment]
I have noticed a bug when scrolling through a list of screen recordings. When there are more than two recordings, the list starts to glitch. This is because the thumbnails are being generated every time an item enters the viewport.
So I don't recommend merging this PR just yet.

**Comment by SuhasDissa** [comment]
Hey there!

I'm happy to tell you that I've fixed the glitching by loading all the data into a ViewModel. I didn't expect this to take as long as it did, but I had to do some major code refactoring to get it to work.

I hope you're okay with the changes I made. If not, no worries! You can just ignore this PR.

Thanks,

**Comment by Bnyro** [comment]
Thank you, that looks very promising!
I'd never ignore a PR that someone opened at one of my repos (unless it's a bot PR), so you can drop that note next time ;)
Unfortunately I'm not at home currently and won't be able to test and review your  changes before Saturday, so please stay patient in the meanwhile.
Cheers

**Comment by Bnyro** [comment]
Works fine from my testings and not much to complain about, only pushed some minor style changes.

I really love using a view pager, that makes the user experience so much better :)

Thank you!

**Pull request merged**
